version: '3.3'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      DATABASE_URL: mysql://root:password@localhost:3306/appsemble
    ports:
      - '3306:3306'
