context:
  development:
    organization: appsemble
    private: false
    remote: http://localhost:9999
    template: true
  production:
    id: 14
    private: false
    remote: https://appsemble.app
    template: true
  review:
    organization: appsemble
    private: false
    template: true
  staging:
    organization: appsemble
    private: false
    remote: https://staging.appsemble.review
    template: true
