name: Waarnemingen App
defaultPage: Maak waarneming


theme:
  themeColor: '#eb0000'


definitions:
  waarneming:
    type: object
    required:
      - onderwerp
      - notities
      - proces
    properties:
      locatie:
        title: GeoCoordinates
        type: object
        properties:
          latitude:
            type: number
          longitude:
            type: number
      onderwerp:
        title: Onderwerp
        type: string
      fotos:
        title: Foto’s
        type: array
        items:
          type: string
          appsembleFile:
            type:
              - image/jpeg
      gebied:
        type: string
        readOnly: true
      notities:
        title: Notities
        type: string
      id:
        type: string
        readOnly: true
      proces:
        title: Proces
        enum:
          - Fietsknip team
          - Handhaving
          - Heel en Groen
          - Inzameling
      created_at:
        type: string
        format: date-time
        readOnly: true


authentication:
  - method: email
    url: https://api.stadswerken.amsterdam/login
    refreshURL: https://api.stadswerken.amsterdam/token/refresh


pages:
  - name: Maak waarneming
    scope:
      - '*'
    blocks:
      - type: form
        parameters:
          fields:
            - name: locatie
              label: Locatie
              type: geocoordinates
            - name: proces
              label: Proces
              enum:
                - value: Fietsknip team
                - value: Handhaving
                - value: Heel en Groen
                - value: Inzameling
            - name: onderwerp
              label: Onderwerp
              type: string
            - name: notities
              label: Notities
              type: string
              multiline: true
            - name: fotos
              label: Foto’s
              type: file
              accept:
                - image/jpeg
              repeated: true
        actions:
          submit:
            type: request
            method: post
            url: 'https://api.stadswerken.amsterdam/waarnemingen_real'
            schema:
              $ref: /definitions/waarneming
            blobs:
              type: upload
              method: post
              url: 'http://oscity.nl:9808/upload'
              serialize: custom
          submitSuccess:
            type: link
            to: Overzichtskaart

  - name: Overzichtskaart
    scope:
      - '*'
    blocks:
      - type: map
        parameters:
          latitude: locatie.latitude
          longitude: locatie.longitude
        resources:
          marker:
            url: 'https://api.stadswerken.amsterdam/waarnemingen_real?$top=20'
            query: {}
        actions:
          markerClick:
            type: link
            to: Waarneming details
      - type: action-button
        actions:
          click:
            type: link
            to: Maak waarneming

  - name: Waarneming details
    scope:
      - '*'
    parameters:
      - id
    blocks:
      - type: detail-viewer
        parameters:
          schema:
            $ref: /definitions/waarneming
          fields:
            - locatie
            - proces
            - onderwerp
            - notities
            - fotos
        actions:
          load:
            type: request
            url: 'https://api.stadswerken.amsterdam/waarnemingen_real/{id}'
