name: Waarnemingen App
defaultPage: Maak waarneming


definitions:
  waarneming:
    type: object
    required:
      - location
      - process
      - description
      - photo
    properties:
      location:
        title: Locatie
        type: string
      process:
        title: Proces
        enum:
          - Fietsknip team
          - Handhaving
          - Heel en Groen
          - Inzameling
      description:
        title: Beschrijving
        type: string
        maxLength: 100
      photo:
        title: Foto’s
        type: string
        appsembleFile:
          type:
            - image/*


authentication:
  - method: email
    url: http://oscity.nl:9808/login
    refreshURL: http://oscity.nl:9808/token/refresh


pages:
  - name: Maak waarneming
    scope:
      - '*'
    blocks:
      - type: form
        parameters:
          schema:
            $ref: /definitions/waarneming
        actions:
          submit:
            type: log

  - name: Overzichtskaart
    scope:
      - '*'
    blocks:
      - type: map
        resources:
          marker:
            url: 'http://oscity.nl:9808/waarnemingen_real'
            query: {}
        actions:
          markerClick:
            type: log
      - type: action-button
        actions:
          click:
            type: link
            to: Verstuur waarneming

  - name: Waarneming details
    blocks:
      - type: detail-viewer
        parameters:
          schema:
            $ref: /definitions/waarneming
