name: Waarnemingen App
defaultPage: Maak waarneming


definitions:
  waarneming:
    type: object
    required:
      - onderwerp
      - notities
      - proces
    properties:
      location:
        title: GeoCoordinates
        type: object
        properties:
          latitude:
            type: number
          longitude:
            type: number
      onderwerp:
        title: Onderwerp
        type: string
      fotos:
        title: Foto’s
        type: array
        items:
          type: string
          appsembleFile:
            type:
              - image/*
      gebied:
        type: string
        readOnly: true
      notities:
        title: Notities
        type: string
      id:
        type: string
        readOnly: true
      proces:
        title: Proces
        enum:
          - Fietsknip team
          - Handhaving
          - Heel en Groen
          - Inzameling
      locatie:
        type: string
        readOnly: true
      created_at:
        type: string
        format: date-time
        readOnly: true


authentication:
  - method: email
    url: http://oscity.nl:9808/login
    refreshURL: http://oscity.nl:9808/token/refresh


pages:
  - name: Maak waarneming
    scope:
      - '*'
    blocks:
      - type: form
        parameters:
          schema:
            $ref: /definitions/waarneming
          hidden:
            - gebied
            - id
            - locatie
            - created_at
        actions:
          submit:
            type: log

  - name: Overzichtskaart
    scope:
      - '*'
    blocks:
      - type: map
        resources:
          marker:
            url: 'http://oscity.nl:9808/waarnemingen_real'
            query: {}
        actions:
          markerClick:
            type: link
            to: Waarneming details
      - type: action-button
        actions:
          click:
            type: link
            to: Maak waarneming

  - name: Waarneming details
    parameters:
      - id
    blocks:
      - type: detail-viewer
        parameters:
          schema:
            $ref: /definitions/waarneming
