name: Waarnemingen
defaultPage: Maak waarneming

theme:
  splashColor: '#FFFFFF'
  themeColor: '#eb0000'

definitions:
  waarneming:
    type: object
    required:
      - notities
      - proces
    properties:
      locatie:
        title: GeoCoordinates
        type: object
        required:
          - latitude
          - longitude
        properties:
          latitude:
            type: number
          longitude:
            type: number
      fotos:
        title: Foto’s
        type: array
        items:
          type: string
          appsembleFile:
            type:
              - image/jpeg
      notities:
        title: Notities
        type: string
      proces:
        title: Proces
        enum:
          - Fietsknip team
          - Handhaving
          - Heel en Groen
          - Inzameling

authentication:
  - method: email
    url: https://api.stadswerken.amsterdam/login
    refreshURL: https://api.stadswerken.amsterdam/token/refresh

pages:
  - name: Maak waarneming
    scope:
      - '*'
    blocks:
      - type: form
        parameters:
          fields:
            - name: locatie
              label: Locatie
              type: geocoordinates
            - name: proces
              label: Proces
              enum:
                - value: Fietsknip team
                - value: Handhaving
                - value: Heel en Groen
                - value: Inzameling
            - name: notities
              label: Notities
              type: string
              multiline: true
            - name: fotos
              label: Foto’s
              type: file
              accept:
                - image/jpeg
              repeated: true
        actions:
          submit:
            type: splash
            blocks:
              - type: amsterdam-splash
                actions:
                  load:
                    type: request
                    method: post
                    url: 'https://api.stadswerken.amsterdam/waarnemingen_real'
                    blobs:
                      type: upload
                      method: post
                      url: 'https://api.stadswerken.amsterdam/upload'
                      serialize: custom
                  error:
                    type: splash.error
                  success:
                    type: link
                    to: Overzichtskaart

  - name: Overzichtskaart
    scope:
      - '*'
    blocks:
      - type: map
        parameters:
          latitude: locatie.latitude
          longitude: locatie.longitude
        resources:
          marker:
            url:
              'https://api.stadswerken.amsterdam/waarnemingen_real?$orderBy=created_at desc&$top=50'
            query: {}
        actions:
          markerClick:
            type: link
            to: Waarneming details
      - type: action-button
        actions:
          click:
            type: link
            to: Maak waarneming

  - name: Waarneming details
    scope:
      - '*'
    parameters:
      - id
    blocks:
      - type: detail-viewer
        parameters:
          fileBase: 'https://api.stadswerken.amsterdam/uploads/'
          schema:
            $ref: /definitions/waarneming
          fields:
            - locatie
            - proces
            - notities
            - fotos
        actions:
          load:
            type: request
            url: 'https://api.stadswerken.amsterdam/waarnemingen_real/{id}'
