name: Waarnemingen
defaultPage: Maak waarneming

theme:
  splashColor: '#FFFFFF'
  themeColor: '#eb0000'
  primaryColor: '#eb0000'

resources:
  waarneming:
    url: https://api.stadswerken.amsterdam/waarnemingen_real
    blobs:
      url: 'https://api.stadswerken.amsterdam/upload'
      serialize: custom
  waarnemingReply:
    references:
      waarneming: id
    schema:
      type: object
      required:
        - content
      properties:
        content:
          type: string

authentication:
  - method: email
    url: https://api.stadswerken.amsterdam/login
    refreshURL: https://api.stadswerken.amsterdam/token/refresh

pages:
  - name: Maak waarneming
    scope:
      - '*'
    blocks:
      - type: form
        version: 0.5.0
        parameters:
          fields:
            - name: locatie
              label: Locatie
              type: geocoordinates
            - name: proces
              label: Proces
              enum:
                - value: Fietsknip team
                - value: Handhaving
                - value: Heel en Groen
                - value: Inzameling
            - name: notities
              label: Notities
              placeholder: Bijv. Er ligt een fiets in de bosjes.
              type: string
              multiline: true
            - name: fotos
              label: Foto’s
              type: file
              accept:
                - image/jpeg
              repeated: true
        actions:
          submit:
            type: dialog
            fullscreen: true
            blocks:
              - type: '@amsterdam/splash'
                version: 0.5.0
                actions:
                  load:
                    type: resource.create
                    resource: waarneming
                  error:
                    type: dialog.error
                  success:
                    type: link
                    to: Overzichtskaart

  - name: Overzichtskaart
    scope:
      - '*'
    blocks:
      - type: map
        version: 0.5.0
        parameters:
          latitude: locatie.latitude
          longitude: locatie.longitude
        actions:
          markerClick:
            type: link
            to: Waarneming details
          load:
            type: resource.query
            resource: waarneming
            query:
              $orderBy: 'created_at desc'
              $top: 50
      - type: action-button
        version: 0.5.0
        actions:
          click:
            type: link
            to: Maak waarneming

  - name: Waarnemingen lijst
    scope:
      - '*'
    blocks:
      - type: filter
        version: 0.5.0
        parameters:
          event: updateWaarnemingen
          highlight: proces
          fields:
            - name: proces
              enum:
                - value: Fietsknip team
                - value: Handhaving
                - value: Heel en Groen
                - value: Inzameling
        actions:
          load:
            type: resource.query
            resource: waarneming
            query:
              $orderBy: 'created_at desc'
              $top: 50

      - type: feed
        version: 0.5.0
        parameters:
          listen: updateWaarnemingen
          title: proces
          subtitle: id|upper
          heading: created_at
          picture: fotos.0
          pictureBase: https://api.stadswerken.amsterdam/uploads
          description: notities
          # XXX: make this work more generic?
          contentField: content
          authorField: author
          # XXX: How to get this from resource?
          parentId: waarnemingId
        actions:
          loadReply:
            type: resource.query
            resource: waarnemingReply
          submitReply:
            type: resource.create
            resource: waarnemingReply
          avatarClick:
            type: dialog
            blocks:
              - type: '@amsterdam/action'
                version: 0.5.0
                actions:
                  submit:
                    type: resource.update
                    resource: waarneming
                  success:
                    type: dialog.ok
                  error:
                    type: dialog.error
                parameters:
                  title: VOER ACTIE UIT
                  fields:
                    - name: notities
                      label: pak waarneming op
                      icon: cog
                      color: '#FFFFFF'
                      backgroundColor: '#00AEEF'
                      value: Waarneming opgepakt
                    - name: notities
                      label: meld als opgelost
                      icon: check
                      color: '#FFFFFF'
                      backgroundColor: '#006502'
                      value: Waarneming opgelost
                    - name: proces
                      label: routeer naar
                      icon: paper-plane
                      color: '#FFFFFF'
                      backgroundColor: '#006502'
                      enum:
                        - value: Fietsknip team
                        - value: Handhaving
                        - value: Heel en Groen
                        - value: Inzameling

  - name: Waarneming details
    scope:
      - '*'
    parameters:
      - id
    blocks:
      - type: detail-viewer
        version: 0.5.0
        parameters:
          fileBase: 'https://api.stadswerken.amsterdam/uploads'
          fields:
            - name: locatie
              label: Locatie
              type: geocoordinates
              longitude: longitude # locatie.longitude
              latitude: latitude # locatie.latitude
            - name: proces
              label: Proces
            - name: notities
              label: Notities
            - name: fotos
              label: Foto's
              type: file
              repeated: true
        actions:
          load:
            type: resource.get
            resource: waarneming
