name: Waarnemingen App
pages:
  - name: Maak waarneming
    blocks:
      - type: form
  - name: Verstuur waarneming
    blocks:
      - type: dataSubmitter
  - name: Overzichtskaart
    blocks:
      - type: map
        size: 1
      - type: actionButton
        actions:
          click:
            type: link
            to: Verstuur waarneming
  - name: Waarneming details
    blocks:
      - type: cardviewer
