name: Waarnemingen
defaultPage: Maak waarneming

theme:
  splashColor: '#FFFFFF'
  themeColor: '#eb0000'

resources:
  waarneming:
    url: https://api.stadswerken.amsterdam/waarnemingen_real
    blobs:
      url: 'https://api.stadswerken.amsterdam/upload'
      serialize: custom

authentication:
  - method: email
    url: https://api.stadswerken.amsterdam/login
    refreshURL: https://api.stadswerken.amsterdam/token/refresh

pages:
  - name: Maak waarneming
    scope:
      - '*'
    blocks:
      - type: form
        version: 1.0.0
        parameters:
          fields:
            - name: locatie
              label: Locatie
              type: geocoordinates
            - name: proces
              label: Proces
              enum:
                - value: Fietsknip team
                - value: Handhaving
                - value: Heel en Groen
                - value: Inzameling
            - name: notities
              label: Notities
              placeholder: Bijv. Er ligt een fiets in de bosjes.
              type: string
              multiline: true
            - name: fotos
              label: Foto’s
              type: file
              accept:
                - image/jpeg
              repeated: true
        actions:
          submit:
            type: splash
            blocks:
              - type: '@amsterdam/splash'
                version: 1.0.0
                actions:
                  load:
                    type: resource.create
                    resource: waarneming
                  error:
                    type: splash.error
                  success:
                    type: link
                    to: Overzichtskaart

  - name: Overzichtskaart
    scope:
      - '*'
    blocks:
      - type: map
        version: 1.0.0
        parameters:
          latitude: locatie.latitude
          longitude: locatie.longitude
        resources:
          marker:
            url:
              'https://api.stadswerken.amsterdam/waarnemingen_real?$orderBy=created_at desc&$top=50'
            query: {}
        actions:
          markerClick:
            type: link
            to: Waarneming details
      - type: action-button
        version: 1.0.0
        actions:
          click:
            type: link
            to: Maak waarneming

  - name: Waarneming details
    scope:
      - '*'
    parameters:
      - id
    blocks:
      - type: detail-viewer
        version: 1.0.0
        parameters:
          fileBase: 'https://api.stadswerken.amsterdam/uploads'
          fields:
            - name: locatie
              label: Locatie
              type: geocoordinates
              longitude: longitude # locatie.longitude
              latitude: latitude # locatie.latitude
            - name: proces
              label: Proces
            - name: notities
              label: Notities
            - name: fotos
              label: Foto's
              type: file
              repeated: true
        actions:
          load:
            type: resource.get
            resource: waarneming
