overrides:
  - files:
      - 'src/**'
    extends:
      - remcohaszing/preact
    rules:
      react/jsx-no-bind:
        - error
        - allowArrowFunctions: true
      react/prop-types: off
      react/sort-comp: off
