apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "appsemble.fullname" . }}-migrate
  labels:
    {{ include "appsemble.labels" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '0'
spec:
  template:
    metadata:
      annotations:
        {{ include "appsemble.gitlab" . | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "appsemble.fullname" . }}-migrate
          image: "{{ .Values.image.repository }}:{{ include "appsemble.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - appsemble
            - migrate
            {{ with .Values.migrateTo }}
            - {{ . }}
            {{ end }}
          env:
{{ include "appsemble.postgres" . | indent 12 }}
            {{- with .Values.sentrySecret }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ . | quote }}
                  key: dsn
            {{- end }}
            {{- with .Values.sentryEnvironment }}
            - name: SENTRY_ENVIRONMENT
              value: {{ . | quote }}
            {{- end }}
