apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "appsemble.fullname" . }}-migrate
  annotations:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "appsemble.name" . }}
    helm.sh/chart: {{ include "appsemble.chart" . }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "appsemble.fullname" . }}-migrate
          image: "{{ .Values.image.repository }}:{{ include "appsemble.tag" . }}"
          command: [node, -r, esm, packages/server, migrate]
