apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "appsemble.fullname" . }}-migrate
  annotations:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "appsemble.name" . }}
    helm.sh/chart: {{ include "appsemble.chart" . }}
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "appsemble.fullname" . }}-migrate
          image: "{{ .Values.image.repository }}:{{ include "appsemble.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - node
            - -r
            - esm
            - packages/server
            - migrate
            {{ with .Values.migrateTo }}
            - {{ . }}
            {{ end }}
          env:
            - name: DATABASE_HOST
              value: {{ include "call-nested" (list . "mysql" "mysql.fullname") }}
            - name: DATABASE_NAME
              value: {{ .Values.mysql.mysqlDatabase }}
            - name: DATABASE_USER
              value: {{ .Values.mysql.mysqlUser }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "call-nested" (list . "mysql" "mysql.secretName") }}
                  key: mysql-password
