apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.existingSecret }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "appsemble.name" . }}
    helm.sh/chart: {{ include "appsemble.chart" . }}
data:
  {{ if .Values.mysql.mysqlPassword }}
  mysql-password:  {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  {{ else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
  {{ if .Values.mysql.mysqlRootPassword }}
  mysql-root-password:  {{ .Values.mysql.mysqlRootPassword | b64enc | quote }}
  {{ else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
