{{ if .Values.provision }}
{{ $clientCredentials := split ":" .Values.provision.account.clientCredentials }}
{{ $userId := uuidv4 }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "appsemble.fullname" . }}-provision
  labels:
    {{ include "appsemble.labels" . }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: '1'
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "appsemble.fullname" . }}-provision
          image: "bitnami/postgresql:11"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - psql
          args:
            - "--command"
            - |
              BEGIN;
                INSERT INTO "User" (id, name, "primaryEmail", created, updated) VALUES (
                  {{ $userId | squote }},
                  {{ .Values.provision.account.name | squote }},
                  {{ .Values.provision.account.email | squote }},
                  NOW(),
                  NOW()
                );
                INSERT INTO "EmailAuthorization" (email, verified, created, updated, "UserId") VALUES (
                  {{ .Values.provision.account.email | squote }},
                  true,
                  NOW(),
                  NOW(),
                  {{ $userId | squote }}
                );
                INSERT INTO "OAuth2ClientCredentials" (id, secret, description, scopes, created, "UserId") VALUES (
                  {{ $clientCredentials._0 | squote }},
                  {{ ($clientCredentials._1 | htpasswd "" | split ":")._1 | squote }},
                  'Used for provisioning the review environment',
                  'apps:write blocks:write organizations:write',
                  NOW(),
                  {{ $userId | squote }}
                );
              COMMIT;
          env:
            - name: PGHOST
              value: {{ .Values.postgresql.fullnameOverride }}
            - name: PGPORT
              value: {{ .Values.global.postgresql.servicePort | quote }}
            - name: PGDATABASE
              value: {{ .Values.global.postgresql.postgresqlDatabase }}
            - name: PGUSER
              value: {{ .Values.global.postgresql.postgresqlUsername }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.postgresql.existingSecret }}
                  key: postgresql-password
{{ end }}
