apiVersion: v2
name: appsemble
version: 0.18.10
appVersion: 0.18.10
kubeVersion: '>=1.20.0'
type: application
description: The official Helm chart for Appsemble.
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 8.9.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/images: |
    - name: appsemble
      image: appsemble/appsemble:0.18.10
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
