apiVersion: v2
name: appsemble
version: 0.24.13
appVersion: 0.24.13
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Server: Add an endpoint that fetches all demo app members without security."
    - kind: added
      description: "Studio: New action documentation section including code snippets."
    - kind: changed
      description: "App: Users can now directly select with which demo user to login,
        without logging in with Appsemble first."
    - kind: fixed
      description: "App: Fixed a bug in the app side menu when the user is still not logged in."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
