apiVersion: v2
name: appsemble
version: 0.24.1
appVersion: 0.24.1
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Cli: Add clonable to asset publish command."
    - kind: added
      description: "Node-utils: Add the option to expire resources based on period.
        Add clonable and ephemeral to resource parsing."
    - kind: added
      description: "Scripts: Add user.properties validation in docs."
    - kind: added
      description: "Server: Add user.properties parsing and validation to app member
        endpoints. Add reseed demo app endpoint. Add demo app logic for resources
        endpoints. Add demo app logic for assets endpoints. Add AppMember
        BeforeCreate and BeforeUpdate hooks for user.properties validation. Add
        Resource BeforeDelete hook for user.properties update. Add logic for demo
        apps to get the user who seeded the resource on action permission validation
        instead of the logged in one."
    - kind: added
      description: "Studio: Add reseed button for demo apps."
    - kind: added
      description: "Types: Add UserProperties interface. Add $seed and $ephemeral to resources."
    - kind: added
      description: "Utils: Add clonable to publish assets endpoint. Add
        user.properties to app definition. Add user.properties to user actions. Add
        demo app reseed endpoint."
    - kind: changed
      description: "Cli: Change cleanup resources script to clean up resources and
        assets based on the new ephemeral field."
    - kind: changed
      description: "Utils: Change properties description in user.register, user.create
        and user.update actions."
    - kind: fixed
      description: "App: Fix user.properties in UserProvider. Fix user.properties in
        user actions."
    - kind: fixed
      description: "Studio: Fix user.properties modal form."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
