apiVersion: v2
name: appsemble
version: 0.19.1
appVersion: 0.19.1
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: 'App: Add user.register, user.login, and user.update actions.'
    - kind: added
      description: 'App: Add account settings to app settings page if the user is logged in.'
    - kind: added
      description: >-
        App: Add password login method for apps. This allows users to register
        accounts for apps without having to go through the Appsemble Studio.
    - kind: added
      description: >-
        Studio: The graphical JSON schema editor now supports the multiline
        property.
    - kind: added
      description: 'Utils: Add the app: locale remapper.'
    - kind: added
      description: 'Utils: Add the null.strip remapper.'
    - kind: fixed
      description: 'Cli: Keep block message overrides when extracting app messages.'
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
