apiVersion: v2
name: appsemble
version: 0.20.3
appVersion: 0.20.3
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "App: Add security.teams property in app definition."
    - kind: added
      description: "App: Add team.invite action."
    - kind: added
      description: "App: Add page for accepting team invites."
    - kind: added
      description: "App: Add support for replacing existing login and register pages
        with custom pages by naming the pages Login or Register."
    - kind: added
      description: "Server: Add support for team invites."
    - kind: changed
      description: "Block(chart): Make min and max in yAxis property optional."
    - kind: changed
      description: "Studio: Replace the JSON schema representation of block parameters
        and definitions with the one used to render out app resource schema."
    - kind: fixed
      description: "Cli: Fix issue where the description for $any actions and events
        were not extracted."
    - kind: fixed
      description: "Studio: Fix issue where block documentation would not render any
        types that used anyOf or oneOf."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
