apiVersion: v2
name: appsemble
version: 0.20.43
appVersion: 0.20.43
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Block(table): Support custom size of image in table cell."
    - kind: added
      description: "Block(table): Support images in table cell."
    - kind: added
      description: "Server: Support authentication for the request action using app
        service secrets when proxied."
    - kind: added
      description: "Studio: Add service secrets to app secrets page."
    - kind: added
      description: "Utils: Add log remapper."
    - kind: added
      description: "Utils: Add match remapper."
    - kind: added
      description: "Utils: Add not remapper."
    - kind: changed
      description: "Block(form): The form block now uses actions to autofill form fields."
    - kind: fixed
      description: "Block(form): Resolve date fields and boolean field missing form
        values when remapping in required requirement."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
