apiVersion: v2
name: appsemble
version: 0.20.9
appVersion: 0.20.9
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Block(form): Add alwaysValidate option to form requirements. This
        can be useful for fields that can also perform validation on fields that are
        filled in at a later time."
    - kind: added
      description: "Block(form): Add confirm option to date and date-time fields.
        Enabling this will display a confirm button once a date has been selected."
    - kind: added
      description: "Block(form): Add dateFormat property to date and date-time fields
        to customize the way these are shown to the user."
    - kind: added
      description: "Block(image): Add image block."
    - kind: changed
      description: "Studio: Sort custom messages section in app translations alphabetically."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
