apiVersion: v2
name: appsemble
version: 0.25.0
appVersion: 0.25.0
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Cli: More options to the create app command."
    - kind: added
      description: "Cli: Option to disable seeding demo apps in publish app command."
    - kind: added
      description: "Cli: Option to disable seeding demo apps in update app command."
    - kind: added
      description: "Server: A setting to disable seeding for demo apps."
    - kind: added
      description: "Studio: New documentation page explaining app concept and various
        app settings."
    - kind: changed
      description: "Studio: The app snapshot editor now uses a split view."
    - kind: fixed
      description: "App: Blocks were incorrectly filtered, which caused blocks of the
        same type to be filtered only by their name, excluding their version,
        resulting in their JavaScript not being loaded."
    - kind: fixed
      description: "React-components: Solve issue where sidebar backdrop covers the
        sidebar itself."
    - kind: fixed
      description: "Server: Disallow request action calling itself."
    - kind: fixed
      description: "Server: In demo mode ephemeral resources with assets would fail to
        create if not initially seeded."
    - kind: fixed
      description: "Studio: App collections page will no longer show an unusable
        dropdown next to the Edit button."
    - kind: fixed
      description: "Studio: Loading the studio at the style editor page no longer
        crashes the page."
    - kind: fixed
      description: "Studio: The app snapshot editor was only 5 pixels high making
        difficult to view."
    - kind: fixed
      description: "Studio: The resource details editor was only 5 pixels high making
        difficult to view."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
