apiVersion: v2
name: appsemble
version: 0.27.10
appVersion: 0.27.10
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Cli: Read README files from app variant directories."
    - kind: added
      description: "Cli: Read app long descriptions per language from README files."
    - kind: added
      description: "Server: Add new table AppReadme to store app long descriptions."
    - kind: added
      description: "Utils: Add readmeUrl to App."
    - kind: changed
      description: "Server: Collections endpoint returns localized results."
    - kind: removed
      description: "Server: Remove column longDescription from App model."
    - kind: removed
      description: "Utils: Remove longDescription from App."
    - kind: fixed
      description: "Block(form): Use field name as fallback value for label if label
        isn’t specified."
    - kind: fixed
      description: "Cli: The app patch command would fail when passing only arguments
        with their values set to false."
    - kind: fixed
      description: "Cli: The app patch command would lock the app before patching
        other values first."
    - kind: fixed
      description: "Preact-components: Use required property from props in dual slider
        component."
    - kind: fixed
      description: "Server: Randonly generated app path length should be less than 30
        characters."
    - kind: fixed
      description: "Server: Subdomains of the main Appsemble host are assumed to have
        a valid SSL certificate if the --forceProtocolHttps flag is set. This
        assumes that the main Appsemble host has a valid wildcard SSL certificate."
    - kind: fixed
      description: "Studio: Localization for collections page app card."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
