apiVersion: v2
name: appsemble
version: 0.19.10
appVersion: 0.19.10
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Block(markdown): Add alignment property. This can be used to
        change the alignment of the text content."
    - kind: added
      description: "Block(markdown): Add centered property to parameters. This can be
        used to center the content without having to use the html block or include
        HTML tags in the messages."
    - kind: added
      description: "Cli: Add support for uploading CSV files."
    - kind: added
      description: "Studio: Add an export to CSV button for app members."
    - kind: fixed
      description: "Studio: Fix download CSV button."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
