apiVersion: v2
name: appsemble
version: 0.18.18
appVersion: 0.18.18
kubeVersion: '>=1.20.0'
type: application
description: The open source low-code app building platform
icon: 'https://charts.appsemble.com/icon.svg'
home: 'https://appsemble.com'
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - 'https://gitlab.com/appsemble/appsemble'
  - 'https://gitlab.com/appsemble/charts'
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: 'App: Add Russian translations.'
    - kind: added
      description: >-
        Appsemble: Add progress property to flow pages. This can be used to set the
        method used to display the progress of a flow page’s steps.
    - kind: added
      description: 'Studio: Add Russian translations.'
    - kind: changed
      description: >-
        Appsemble: Change the background color of corner-dots in flow pages. More
        often than not these ended up being invisible due to the default background
        color.
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
