apiVersion: v2
name: appsemble
version: 0.18.15
appVersion: 0.18.15
kubeVersion: '>=1.20.0'
type: application
description: The open source low-code app building platform
icon: 'https://charts.appsemble.com/icon.svg'
home: 'https://appsemble.com'
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - 'https://gitlab.com/appsemble/appsemble'
  - 'https://gitlab.com/appsemble/charts'
dependencies:
  - name: postgresql
    version: 8.9.6
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: 'Studio: Add core app message translations to the translations page.'
    - kind: changed
      description: 'Server: Block organization IDs that could be used to impersonate Appsemble.'
    - kind: changed
      description: 'Server: Redirect to Appsemble Studio for app-like URLs.'
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
