apiVersion: v2
name: appsemble
version: 0.20.39
appVersion: 0.20.39
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Block(form): Support disabled options in enum fields."
    - kind: added
      description: "App: Add layout option to set the position of a message on the screen."
    - kind: added
      description: "App: Add match action."
    - kind: added
      description: "App: Add support for deeply nested array remappers."
    - kind: added
      description: "App: Add translation path for the first subpage in the loop page."
    - kind: added
      description: "App: Add translation path for the last subpage in the loop page."
    - kind: added
      description: "Server: Add support for deeply nested array remappers."
    - kind: changed
      description: "Block(form): Child fields in repeated object fields now contain an
        index in their naming sequence, breaking styling in some instances when
        applied to child fields."
    - kind: changed
      description: "Block(form): Object field is now usable within another object field."
    - kind: changed
      description: "Block(form): Rename object field to fieldset. Apps using the
        object field that need to be updated to version 0.20.39 will break. To fix
        this, change the field type from object to fieldset."
    - kind: fixed
      description: "Block(form): Required remapper is now properly supported in nested fields."
    - kind: fixed
      description: "Block(form): Resolve validation issue causing object fields to be broken."
    - kind: fixed
      description: "App: Apply the same translation path for all subpages between the
        first and last subpage in the loop page."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
