apiVersion: v2
name: appsemble
version: 0.27.9
appVersion: 0.27.9
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Cli: Add app patch command to update the settings of an app."
    - kind: added
      description: "Cli: Support variant argument for app publish command."
    - kind: added
      description: "Cli: Support variant argument for app update command."
    - kind: added
      description: "Cli: Support assets option in appsembleRC file to publish assets
        from assets folder."
    - kind: added
      description: "Cli: Support resources option in appsembleRC file to publish
        resources from resources folder."
    - kind: added
      description: "Cli: Support shared app variants using the variant: name in an
        .appsemblerc context."
    - kind: changed
      description: "Cli: Fix uploading screenshots with app update."
    - kind: fixed
      description: "Cli: Fix reading supported languages for screenshots."
    - kind: fixed
      description: "Cli: Fix reading supported languages from the app directory
        instead of the main project."
    - kind: fixed
      description: "Cli: The app publish command would error when no context is defined."
    - kind: fixed
      description: "Cli: The app update command would error when no context is defined."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
