apiVersion: v2
name: appsemble
version: 0.23.6
appVersion: 0.23.6
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Studio: #Add a full screen button to code and GUI editor pages."
    - kind: added
      description: "Studio: #Add support for multiple screen aspect ratios and resolutions."
    - kind: added
      description: "Studio: #Add the ability to choose the device’s screen format."
    - kind: added
      description: "Studio: #Keep full screen state reference."
    - kind: changed
      description: "Studio: #Automatically hide the side menu on code and GUI editor
        pages - use burger menu to reveal it."
    - kind: changed
      description: "Studio: #Hide app preview when the screen width is too small."
    - kind: changed
      description: "Studio: #support multiple devices for app preview."
    - kind: fixed
      description: "React-components: #Fix the position of the dropdown button icon."
    - kind: fixed
      description: "Studio: #Fix CSS class selectors for indentation pseudo components."
    - kind: fixed
      description: "Studio: #Resize Monaco editor and app preview."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
