apiVersion: v2
name: appsemble
version: 0.27.11
appVersion: 0.27.11
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Cli: Support uploading maskable-icon.png from app variant
        directory with app publish and app update."
    - kind: changed
      description: "Server: Change SSO authorizations to cascade delete for OAuth2 and SAML."
    - kind: fixed
      description: "Cli: Uploading icon.png from app variant directory with app
        publish and app update."
    - kind: fixed
      description: "Server: Allow user info url to be empty when calling endpoint
        updateAppOAuth2Secret."
    - kind: fixed
      description: "Server: Creating an OAuth2 app secret would break the ability to
        update again without a page refresh."
    - kind: fixed
      description: "Studio: The app assets tab would show an error after deleting the
        last asset."
    - kind: fixed
      description: "Studio: The app resources tab would show an error after deleting
        the last resource."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
