apiVersion: v2
name: appsemble
version: 0.24.12
appVersion: 0.24.12
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Cli: Publish resources recursively in the app publish command
        based on resource references."
    - kind: added
      description: "Server: Reseed resources recursively in the /app/{id}/reseed
        endpoint based on resource references."
    - kind: added
      description: "Server: Reseed resources recursively in the
        cleanupResourcesAndAssets command based on resource references."
    - kind: changed
      description: "Node-utils: Patch resource schema in processResourceBody to allow
        resource references by index."
    - kind: changed
      description: "Utils: Added validation for resource names against the reserved
        keywords created, updated, author, editor, seed, ephemeral, clonable and
        expires."
    - kind: fixed
      description: "App: App bar rendering title wrong."
    - kind: fixed
      description: "Studio: Unexpected error on the organization docs page."
    - kind: fixed
      description: "Utils: Remove additional history stack in the remapper context."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
