apiVersion: v2
name: appsemble
version: 0.18.30
appVersion: 0.18.30
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: 'Block(html): Add data event listener.'
    - kind: added
      description: 'Block(markdown): Add data event listener.'
    - kind: added
      description: 'App: Add data option to page remapper.'
    - kind: added
      description: >-
        App: Add random.choice remapper. It returns a random entry from an array of
        items, or the input if the input is not an array.
    - kind: added
      description: 'App: Add storage.read and storage.write actions.'
    - kind: added
      description: 'Studio: Render Monaco editor diagnostics below the editor pane.'
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
