apiVersion: v2
name: appsemble
version: 0.24.0
appVersion: 0.24.0
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Block(form): Add support for icon inside file entry."
    - kind: added
      description: "Block(form): Add support for icon to geocoordinates field."
    - kind: added
      description: "Block(form): Add support for icon to static field."
    - kind: added
      description: "Block(form): Add support for label to geocoordinates field."
    - kind: added
      description: "Block(form): Add support for tag to geocoordinates field."
    - kind: added
      description: "Block(form): Add support for “required‘ requirement to
        geocoordinates field."
    - kind: added
      description: "App: Remap query remapper on the client when request action
        requests are proxied."
    - kind: added
      description: "Preact-components: Add icon right option to render icon on the right."
    - kind: added
      description: "Preact-components: Add styling to dual slider when it has an icon."
    - kind: added
      description: "Preact-components: Add styling to slider when it has an icon."
    - kind: added
      description: "Preact-components: Add support for icon to dual slider field."
    - kind: added
      description: "Preact-components: Add support for icon to slider field."
    - kind: added
      description: "Studio: Add a button for mobile devices to open and show the app preview."
    - kind: added
      description: "Studio: Add option to pass down class name to the editor tab
        component`s elements."
    - kind: added
      description: "Studio: Add option to set the dropdown content container to the right side."
    - kind: changed
      description: "Block(form): Change icon implementation, convert Font Awesome icon
        to SVG instead."
    - kind: changed
      description: "Cli: Update definition to include changes."
    - kind: changed
      description: "React-components: Add an extra parameter for a reference to be
        exempt from triggering the closing event."
    - kind: changed
      description: "Server: Rename database model “Member” to “OrganizationMember”."
    - kind: changed
      description: "Studio: Breadcrumbs now hide on smaller mobile devices."
    - kind: changed
      description: "Studio: Change the style of tabs navigator to resize and apply
        styling based on screen size."
    - kind: changed
      description: "Studio: Replace normal buttons with a collapsible navigation bar
        for mobile user interface."
    - kind: changed
      description: "Types: Rename type “Member” to “OrganizationMember” in the code."
    - kind: fixed
      description: "Block(form): Fix default min and max value for range input field."
    - kind: fixed
      description: "Block(form): Fix list input field styling when icon is present."
    - kind: fixed
      description: "Block(form): Fix the file entry’s image source."
    - kind: fixed
      description: "React-components: Fix GUI path name matching condition."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
