apiVersion: v2
name: appsemble
version: 0.20.21
appVersion: 0.20.21
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Block(form): Add inline property to form fields."
    - kind: added
      description: "Block(form): Allow the required requirement to be remapped for
        conditionally required form fields."
    - kind: added
      description: "App: Add Indonesian translations."
    - kind: added
      description: "App: Add retainFlowData prop to flow page."
    - kind: added
      description: "App: Added Russian translations."
    - kind: added
      description: "Studio: Add Indonesian translations."
    - kind: added
      description: "Studio: Added Russian translations."
    - kind: added
      description: "Types: Add hideName prop to pages."
    - kind: added
      description: "Utils: Add from.history remapper."
    - kind: changed
      description: "Types: array.omit remapper now supports an array of remappers as input."
    - kind: fixed
      description: "App: Resolve link.back action not navigating to the previous page
        if current page is translated."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
