apiVersion: v2
name: appsemble
version: 0.24.11
appVersion: 0.24.11
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Server: Default values are added to nested properties in app
        member properties when they are of type object."
    - kind: changed
      description: "App: If a currentEmail is not specified in the user.update action,
        it assumes the logged-in email."
    - kind: changed
      description: "App: The password field is no longer required in the user.update action."
    - kind: changed
      description: "Utils: Changed user.properties to accept integer and array
        properties without referencing resources."
    - kind: fixed
      description: "App: After the user.update action, updated user properties are now
        correctly assigned."
    - kind: fixed
      description: "App: After updating user properties from the studio, they are now
        correctly assigned."
    - kind: fixed
      description: "App: App controller handler functions now load as expected."
    - kind: fixed
      description: "Server: Invalid authentication state causing internal server error
        on blocks page."
    - kind: fixed
      description: "Studio: The dialog message shown in the studio app editor page
        shows message even after save."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
