apiVersion: v2
name: appsemble
version: 0.18.17
appVersion: 0.18.17
kubeVersion: '>=1.20.0'
type: application
description: The open source low-code app building platform
icon: 'https://charts.appsemble.com/icon.svg'
home: 'https://appsemble.com'
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - 'https://gitlab.com/appsemble/appsemble'
  - 'https://gitlab.com/appsemble/charts'
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: 'App: Add navTitle property to page.'
    - kind: added
      description: 'Studio: Add password strength indicator.'
    - kind: changed
      description: 'Cli: Change the default remote to https://appsemble.app.'
    - kind: fixed
      description: 'Cli: Fix the --ignore-conflict flag behavior.'
    - kind: security
      description: 'Server: Passwords must now be at least 8 characters.'
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
