apiVersion: v2
name: appsemble
version: 0.20.7
appVersion: 0.20.7
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Block(table): Add alignment property to allow for setting the
        alignment of dropdown fields."
    - kind: added
      description: "App: Add lt and gt remappers for comparing if a value if greater
        than or less than another value."
    - kind: added
      description: "App: Add support for setting an end date for the ics remapper.
        This is mutually exclusive with the property duration."
    - kind: added
      description: "Server: Add support for null in OData queries. For example:
        /$filter=date eq null."
    - kind: changed
      description: "Block(tiles): Change default text color to be brighter."
    - kind: changed
      description: "Block(tiles): Rename asset to image. Any value that matches a
        valid URL will be used as the source of the image, otherwise it will attempt
        to load an asset based on either an alias or a UUID."
    - kind: fixed
      description: "Block(tiles): Fix background color. This used to assume the color
        is a valid Bulma color. Instead it will display either a hex value, a valid
        Bulma color, or default to primary."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
