apiVersion: v2
name: appsemble
version: 0.18.28
appVersion: 0.18.28
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: 'Block(tiles): Add tiles block.'
    - kind: added
      description: >-
        Cli: Add --modify-context flag for app create command. This will modify the
        context in .appsemblerc to include the ID of the newly created app.
    - kind: added
      description: 'Cli: Add asset create command.'
    - kind: added
      description: >-
        Cli: Add support for .appsemblerc.yaml context usage for resource and team
        commands using --app <path> and --context <environment> flags.
    - kind: added
      description: >-
        Sdk: The IconName type from @fortawesome/fontawesome-common-types is now
        re-exported by the SDK.
    - kind: added
      description: 'Server: Add option to define annotations when creating a team.'
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
