apiVersion: v2
name: appsemble
version: 0.18.19
appVersion: 0.18.19
kubeVersion: '>=1.20.0'
type: application
description: The open source low-code app building platform
icon: 'https://charts.appsemble.com/icon.svg'
home: 'https://appsemble.com'
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - 'https://gitlab.com/appsemble/appsemble'
  - 'https://gitlab.com/appsemble/charts'
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: 'https://charts.bitnami.com/bitnami'
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: >-
        Server: Add new option --sentry-allowed-domains to only serve Sentry on apps
        from specific domains.
    - kind: changed
      description: >-
        App: Sync up bottom navigation with side navigation in terms of the
        available options based on the layout property.
    - kind: removed
      description: 'Server: Remove block resources.'
    - kind: fixed
      description: 'App: Fix usage of navigation property in pages.'
    - kind: fixed
      description: 'Server: Fix serving maskable app icons.'
    - kind: fixed
      description: 'Studio: Use app icons provided by the API.'
    - kind: fixed
      description: 'Studio: Use block icons provided by the API.'
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
