apiVersion: v2
name: appsemble
version: 0.20.16
appVersion: 0.20.16
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Block(form): Block(form): Add conditional field rendering."
    - kind: added
      description: "App: Add the each action."
    - kind: added
      description: "Server: Add the each action."
    - kind: changed
      description: "App: Upgrade from “react-router-dom” 5.0.0 to 6.0.0."
    - kind: changed
      description: "React-components: Upgrade from “react-router-dom” 5.0.0 to 6.0.0."
    - kind: changed
      description: "Server: Accepts the examples property for JSON schemata instead of example."
    - kind: changed
      description: "Studio: Upgrade from “react-router-dom” 5.0.0 to 6.0.0."
    - kind: fixed
      description: "App: Fix user.register action."
    - kind: fixed
      description: "Server: Fix content security policy for OAuth2 client credentials
        login process."
    - kind: fixed
      description: "Studio: Fixed editor console errors persisting after fixing the error."
    - kind: fixed
      description: "Studio: Studio(blocks): Change name in block examples to type."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
