apiVersion: v2
name: appsemble
version: 0.11.4
description: The official Helm chart for Appsemble.
icon: https://gitlab.com/uploads/-/system/project/avatar/7050597/bitmap.png
home: https://appsemble.com
sources:
  - https://gitlab.com/appsemble/appsemble
appVersion: 0.11.4
dependencies:
  - name: postgresql
    version: 8.3.4
    repository: https://kubernetes-charts.storage.googleapis.com
    condition: postgresql.enabled
