apiVersion: v2
name: appsemble
version: 0.18.22
appVersion: 0.18.22
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: 'App: Add Croatian translations.'
    - kind: added
      description: 'App: Add share action.'
    - kind: added
      description: 'Cli: Added --dry-run option to appsemble app create.'
    - kind: added
      description: 'Server: Add block synchronization with remote Appsemble instances.'
    - kind: added
      description: >-
        Server: Add option to do a dry run of the app creation endpoint. By adding
        ?dryRun=true to the query string, apps can now be validated without having
        to create a new app or using an existing app.
    - kind: added
      description: 'Studio: Add Croatian translations.'
    - kind: changed
      description: 'Cli: Replace typescript-json-schema with ts-json-schema-generator.'
    - kind: changed
      description: 'Cli: The CLI now looks for app-definition.yaml instead of app.yaml.'
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
