apiVersion: v2
name: appsemble
version: 0.19.7
appVersion: 0.19.7
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "App: Add support for link action validation."
    - kind: added
      description: "App: Track page views using Google Analytics if configured."
    - kind: added
      description: "App: Update the document title to the current page."
    - kind: added
      description: "Studio: App CSS is now validated in the editor."
    - kind: added
      description: "Studio: The app editor now shows inline validation errors."
    - kind: changed
      description: "Studio: Rename Roles page for apps in Studio to Users."
    - kind: fixed
      description: "Cli: Fix authentication headers not correctly being passed through
        for Team CLI commands."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
