apiVersion: v2
name: appsemble
version: 0.28.0
appVersion: 0.28.0
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 11.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: >
    - kind: added
      description: "Studio: Add edit and delete buttons on an organization’s app
        collections page."
    - kind: added
      description: "Studio: Add option to view seed resources on the resource details page."
    - kind: changed
      description: "Server: Change the type of the data column in the Resource table
        to optimize performance and support sorting by nested fields."
    - kind: changed
      description: "Utils: Add support for remappers in the prop remapper."
    - kind: fixed
      description: "Block(list): The block would throw an error when there is no data
        instead of displaying the No data message."
    - kind: fixed
      description: "Cli: team update command should use patch request."
    - kind: fixed
      description: "Utils: The date.format remapper would not accept strings."
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
    - name: support
      url: https://gitlab.com/appsemble/appsemble/-/issues
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/container/appsemble/appsemble
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
