apiVersion: v2
name: appsemble
version: 0.18.24
appVersion: 0.18.24
kubeVersion: '>=1.21.0'
type: application
description: The open source low-code app building platform
icon: https://charts.appsemble.com/icon.svg
home: https://appsemble.com
keywords:
  - app
  - apps
  - appsemble
  - framework
  - low-code
  - lowcode
sources:
  - https://gitlab.com/appsemble/appsemble
  - https://gitlab.com/appsemble/charts
dependencies:
  - name: postgresql
    version: 10.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: >-
        Block(button-list): Fix onClick not being used as the default if an action
        isn’t specified.
    - kind: fixed
      description: >-
        Block(markdown): Fix issue where certain data types would not display
        correctly.
    - kind: fixed
      description: 'App: Support remappers in page dialog titles.'
    - kind: fixed
      description: 'Cli: Fix parsing error when verifying YAML messages.'
    - kind: fixed
      description: 'Studio: Fix a crash caused by the editor.'
  artifacthub.io/license: LGPL-3.0-only
  artifacthub.io/links: |
    - name: Appsemble Studio
      url: https://appsemble.app
    - name: Documentation
      url: https://appsemble.app/docs
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
    - url: https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
  artifacthub.io/signKey: |
    fingerprint: C4EE8EE8B16EE94FEA3B0A7C346FF2248F310B53
    url: https://gitlab.com/appsemble-bot.gpg
