replicaCount: 1

image:
  repository: appsemble/appsemble
  tag: null
  pullPolicy: IfNotPresent

app: appsemble
nameOverride: ''
fullnameOverride: ''

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts: []
  tls:
    {}
    # secretName: chart-example-tls

resources:
  {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

smtpSecret: smtp

migrateTo: {}

mysql:
  existingSecret: null
  fullnameOverride: null
  imagePullSecrets: null
  mysqlAllowEmptyPassword: false
  mysqlDatabase: appsemble
  mysqlPassword: null
  mysqlRootPassword: null
  mysqlUser: appsemble
  nameOverride: null
  persistence:
    existingClaim: null
    storageClass: null
    subPath: null
  priorityClassName: null
  schedulerName: null
  service:
    loadBalancerIP: null
    nodePort: null
  subPath: null
  timezone: null
