name: Person
description: A simple form and data viewing app using the resource API
defaultPage: Person Registration Form

resources:
  person:
    schema:
      type: object
      required:
        - firstName
        - lastName
        - email
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        description:
          type: string

pages:
  - name: Person List
    blocks:
      - type: data-loader
        version: 0.15.6
        actions:
          onLoad:
            type: resource.query
            resource: person
        events:
          emit:
            data: data
      - type: table
        version: 0.15.6
        parameters:
          fields:
            - value: { prop: firstName }
              label: First Name
            - value: { prop: lastName }
              label: Surname
        actions:
          onClick:
            to: Person Details
            type: link
        events:
          listen:
            data: data
      - type: action-button
        version: 0.15.6
        parameters:
          icon: plus
        actions:
          onClick:
            to: Person Registration Form
            type: link

  - name: Person Registration Form
    blocks:
      - type: form
        version: 0.15.6
        actions:
          onSubmit:
            type: resource.create
            resource: person
            onSuccess:
              type: link
              to: Person List
        parameters:
          fields:
            - label: First Name
              name: firstName
              type: string
            - label: Surname
              name: lastName
              type: string
            - label: Email
              name: email
              type: string
            - label: Description
              multiline: true
              name: description
              type: string

  - name: Person Details
    parameters:
      - id
    blocks:
      - type: data-loader
        version: 0.15.6
        actions:
          onLoad:
            type: resource.get
            resource: person
        events:
          emit:
            data: data
      - type: detail-viewer
        version: 0.15.6
        parameters:
          fields:
            - value: { prop: firstName }
              label: First Name
            - value: { prop: lastName }
              label: Surname
            - value: { prop: email }
              label: Email Address
            - value: { prop: description }
              label: Description
        events:
          listen:
            data: data
