context:
  development:
    organization: eindhoven
    remote: http://localhost:9999
    template: true
    visibility: public
  production:
    id: 626
    remote: https://appsemble.app
    template: true
    visibility: unlisted
  review:
    organization: eindhoven
    template: true
    visibility: public
  staging:
    organization: eindhoven
    remote: https://staging.appsemble.review
    template: true
    visibility: public
