swagger: '2.0'
info:
  version: '1.0.0'
  title: Appsemble API
  description: |
    The API for the Appsemble / Amsterdam project.
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
