name: Holidays
description: A simple app that fetches holiday information for various countries.
defaultPage: Holidays in NL

pages:
  - name: Holidays in NL
    blocks:
      - type: data-loader
        version: 0.15.1
        actions:
          onLoad:
            url: https://date.nager.at/Api/v2/NextPublicHolidays/NL
            type: request
        events:
          emit:
            data: holidays
      - type: table
        version: 0.15.1
        parameters:
          fields:
            - value:
                prop: date
              label: Date
            - value:
                prop: name
              label: Name (EN)
            - value:
                prop: localName
              label: Name (NL)
        events:
          listen:
            data: holidays

  - name: Holidays in US
    blocks:
      - type: data-loader
        version: 0.15.1
        actions:
          onLoad:
            url: https://date.nager.at/Api/v2/NextPublicHolidays/US
            type: request
        events:
          emit:
            data: holidays
      - type: table
        version: 0.15.1
        parameters:
          fields:
            - value:
                prop: date
              label: Date
            - value:
                prop: name
              label: Name (EN)
        events:
          listen:
            data: holidays

  - name: Holidays in DE
    blocks:
      - type: data-loader
        version: 0.15.1
        actions:
          onLoad:
            url: https://date.nager.at/Api/v2/NextPublicHolidays/DE
            type: request
        events:
          emit:
            data: holidays
      - type: table
        version: 0.15.1
        parameters:
          fields:
            - value:
                prop: date
              label: Date
            - value:
                prop: name
              label: Name (EN)
            - value:
                prop: localName
              label: Name (DE)
        events:
          listen:
            data: holidays

  - name: Holidays in ES
    blocks:
      - type: data-loader
        version: 0.15.1
        actions:
          onLoad:
            url: https://date.nager.at/Api/v2/NextPublicHolidays/ES
            type: request
        events:
          emit:
            data: holidays
      - type: table
        version: 0.15.1
        parameters:
          fields:
            - value:
                prop: date
              label: Date
            - value:
                prop: name
              label: Name (EN)
            - value:
                prop: localName
              label: Name (ES)
        events:
          listen:
            data: holidays
