extends:
  - remcohaszing/react
rules:
  react/jsx-no-bind:
    - error
    - allowArrowFunctions: true
  react/jsx-sort-props:
    - error
    - ignoreCase: true
  react/no-multi-comp:
    - error
    - ignoreStateless: true
  react/prop-types: off
