apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "docs.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ include "docs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - {{ .Values.url | trimPrefix "https://" }}
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.url | trimPrefix "https://" }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "docs.fullname" . }}
              servicePort: http
