context:
  production:
    remote: https://appsemble.app
    template: true
    private: false
    id: 130
  staging:
    remote: https://staging.appsemble.review
    organization: appsemble
    template: true
    private: false
  review:
    organization: appsemble
    template: true
    private: false
  development:
    remote: http://localhost:9999
    organization: appsemble
    template: true
    private: false
