name: Survey
description: An app which asks the user to fill out some questions.
defaultPage: Survey

layout:
  navigation: hidden

resources:
  answer:
    create:
      roles: [$public]
    schema:
      type: object
      required:
        - reached
        - knowsAppsemble
        - usedLowCode
        - lowCodePlatforms
        - usedYaml
      properties:
        reached:
          type: string
        knowsAppsemble:
          type: boolean
        usedLowCode:
          type: boolean
        lowCodePlatforms:
          type: string
        usedYaml:
          type: boolean

anchors:
  - &version 0.18.17

pages:
  - name: Survey
    type: flow
    actions:
      onFlowFinish:
        type: resource.create
        resource: answer
        onSuccess:
          type: link
          to: Finished

    subPages:
      - name: Introduction
        blocks:
          - type: markdown
            version: *version
            layout: static
            parameters:
              content: { translate: introText }
          - type: button-list
            version: *version
            parameters:
              buttons:
                - label: { translate: start }
                  onClick: onStart
                  color: primary
            actions:
              onStart:
                type: flow.next

      - name: Familiarity
        blocks:
          - type: form
            version: *version
            actions:
              onSubmit:
                type: flow.next
              onPrevious:
                type: flow.back
            parameters:
              fields:
                - type: string
                  name: reached
                  multiline: true
                  label: { translate: reached }
                - type: boolean
                  name: knowsAppsemble
                  label: { translate: knowsAppsemble }

      - name: Expertise
        blocks:
          - type: form
            version: *version
            actions:
              onSubmit:
                type: flow.next
              onPrevious:
                type: flow.back
            parameters:
              fields:
                - type: boolean
                  name: usedLowCode
                  label: { translate: usedLowCode }
                - type: string
                  name: lowCodePlatforms
                  multiline: true
                  label: { translate: lowCodePlatforms }
                - type: boolean
                  name: usedYaml
                  label: { translate: usedYaml }

  - name: Finished
    blocks:
      - type: markdown
        version: *version
        layout: static
        parameters:
          content: { translate: finished }
      - type: button-list
        version: *version
        parameters:
          buttons:
            - label: { translate: backToHome }
              onClick: home
              color: primary
        actions:
          home:
            type: link
            to: Survey
