App:
  type: object
  required:
    - name
    - defaultPage
  properties:
    theme:
      $ref: '#/definitions/Theme'
    id:
      type: number
      minimum: 0
      readOnly: true
    name:
      type: string
      maxLength: 30
    defaultPage:
      type: string
      maxLength: 50
    definitions:
      type: object
    authentication:
      type: array
      items:
        type: object
        additionalProperties: false
        required:
          - method
          - url
        properties:
          method:
            enum: [email]
          url:
            type: string
            format: uri
          refreshURL:
            type: string
            format: uri
    pages:
      type: array
      items:
        type: object
        additionalProperties: false
        required:
          - name
          - blocks
        properties:
          name:
            type: string
            maxLength: 50
          parameters:
            type: array
            items:
              type: string
          scope:
            type: array
            items:
              type: string
          blocks:
            type: array
            items:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                  maxLength: 30
                parameters:
                  type: object
                actions:
                  type: object
