App:
  type: object
  required:
    - name
    - defaultPage
  properties:
    id:
      type: number
      minimum: 0
      readOnly: true
    name:
      type: string
      maxLength: 30
    defaultPage:
      type: string
      maxLength: 50
    definitions:
      type: object
    pages:
      type: array
      items:
        type: object
        additionalProperties: false
        required:
          - name
          - blocks
        properties:
          name:
            type: string
            maxLength: 50
          blocks:
            type: array
            items:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                  maxLength: 30
                parameters:
                  type: object
                actions:
                  type: object
