extends:
  - remcohaszing/react
  - remcohaszing/web
rules:
  formatjs/enforce-id:
    - error
    - idInterpolationPattern: 'studio.[sha512:contenthash:base64:6]'
  react/prop-types: off
  react/require-default-props: off
