context:
  development:
    listed: true
    organization: appsemble
    remote: http://localhost:9999
    template: true
  production:
    id: 9
    listed: true
    remote: https://appsemble.app
    template: true
  review:
    listed: true
    organization: appsemble
    template: true
  staging:
    organization: appsemble
    listed: true
    remote: https://staging.appsemble.review
    template: true
