name: My App
description: ''
defaultPage: People

resources:
  person:
    schema:
      type: object
      required:
        - firstName
        - lastName
        - email
      properties:
        firstName:
          type: string
          maxLength: 80
        lastName:
          type: string
          maxLength: 80
        email:
          type: string
          format: email
        description:
          type: string
          maxLength: 500

pages:
  - name: Register
    blocks:
      - type: form
        version: 0.10.0
        parameters:
          fields:
            - name: firstName
              label: First Name
            - name: lastName
              label: Surname
            - name: email
              label: Email Address
              format: email
            - name: description
              label: Description
              multiline: true

  - name: People
    blocks:
      - type: data-loader
        version: 0.10.0
        events:
          emit:
            data: people
        actions:
          onLoad:
            type: resource.query
            resource: person
      - type: list
        version: 0.10.0
        events:
          on:
            data: people
        parameters:
          fields:
            - name: firstName
              label: First Name
            - name: lastName
              label: Surname

  - name: Person details
    parameters:
      - id
    blocks:
      - type: data-loader
        version: 0.10.0
        events:
          emit:
            data: person
        actions:
          onLoad:
            type: resource.get
            resource: person
      - type: detail-viewer
        version: 0.10.0
        events:
          on:
            data: person
        parameters:
          fields:
            - name: firstName
              label: First Name
            - name: lastName
              label: Last Name
            - name: email
              label: Email Address
            - name: description
              label: Description
