swagger: '2.0'
info:
  version: '0.4.2'
  title: Appsemble API
  description: |
    Welcome to the Appsemble API.

    The app editor can be found on
    > http://localhost:9999

    The OpenAPI explorer can be found on
    > http://localhost:9999/api-explorer

    Rendered apps can be found on
    > http://localhost:9999/:id
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
